version = 1

exclude_patterns = [
  "libs/PHPMailer/**",
  "assets/vendor/**",
  "assets/js/vendor/**",
  "assets/css/vendor/**",
  "vendor/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

# CSS analyzer doesn't exist - either remove this or disable it:
# [[analyzers]]
# name = "css"
# enabled = false
