version = 1

exclude_patterns = [
  "libs/PHPMailer/**",
  "assets/vendor/**",
  "assets/js/vendor/**",
  "assets/css/vendor/**",
  "vendor/**",
  "**/*.css",
  "**/*.scss",
  "**/*.less"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true
