version = 1

exclude_patterns = [
  "libs/PHPMailer/**",
  "assets/vendor/**",
  "assets/js/vendor/**",
  "assets/css/vendor/**",
  "vendor/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

# Remove or comment out the css analyzer as it's not supported
# [[analyzers]]
# name = "css"
# enabled = true
